### ISSUE TITLE
Party Chat

### ISSUE THREAD

**Issue by NoahOG** [cyberpwnn/GlacialRealms#261] opened 2016-10-16 21:32 UTC
Party chat goes from skyblock 1 to skyblock 2 and the parties are combined.

**Comment by SwiftSwamp** [comment] 2016-10-16 21:34
This will require a network reboot to fix, guess the last update the Author pushed.. they didn't test it before pushing it and it's half broken. It's fixed, just waiting for the reboot.

**Comment by cyberpwnn** [comment] 2016-10-17 00:55
If the netboot isnt ready but the issue is fixed, ill close it.

**Closed by cyberpwnn** 2016-10-17 00:55 UTC
Labels: < 20 Minutes, bug, general
