### ISSUE TITLE
Skyblock Crash

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#276] opened 2016-10-17 20:15 UTC
Not 100% sure if this is related with Technic but I'm assuming so, Skyblock just crashed with the following crash log;

```
---- Minecraft Crash Report ----
// Oops.

Time: 10/17/16 4:11 PM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at net.minecraft.server.v1_8_R3.TileEntityHopper.r(TileEntityHopper.java:265)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:189)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177)
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:786)
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.server.v1_8_R3.TileEntityHopper.r(TileEntityHopper.java:265)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.m(TileEntityHopper.java:189)
	at net.minecraft.server.v1_8_R3.TileEntityHopper.c(TileEntityHopper.java:177)

-- Block entity being ticked --
Details:
	Name: Hopper // net.minecraft.server.v1_8_R3.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.server.v1_8_R3.BlockHopper)
	Block data value: 3 / 0x3 / 0b0011
	Block location: World: (-3954,48,-5342), Chunk: (at 14,3,2 in -248,-334; contains blocks -3968,0,-5344 to -3953,255,-5329), Region: (-8,-11; contains chunks -256,-352 to -225,-321, blocks -4096,0,-5632 to -3585,255,-5121)
	Actual block type: ID #0 (tile.air // net.minecraft.server.v1_8_R3.BlockAir)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.server.v1_8_R3.World.tickEntities(World.java:1488)
	at net.minecraft.server.v1_8_R3.WorldServer.tickEntities(WorldServer.java:597)
```

**Comment by cyberpwnn** [comment] 2016-10-17 21:06
After searching around, it looks like corrupt hoppers are more of a problem than you would think. It is not technic.

```
 Block type: ID #154 (tile.hopper // net.minecraft.server.v1_8_R3.BlockHopper)
 Block data value: 3 / 0x3 / 0b0011
 Block location: World: (-3954,48,-5342), Chunk: (at 14,3,2 in -248,-334; contains blocks -3968,0,-5344 to -3953,255,-5329), Region: (-8,-11; contains chunks -256,-352 to -225,-321, blocks -4096,0,-5632 to -3585,255,-5121)
 Actual block type: ID #0 (tile.air // net.minecraft.server.v1_8_R3.BlockAir)
 Actual block data value: 0 / 0x0 / 0b0000
```

**Comment by cyberpwnn** [comment] 2016-10-17 21:34
There isnt anything we can do about this, however if it crashes again, compare this issue with the block locations.

**Comment by cyberpwnn** [comment] 2016-10-17 21:46
![image](https://cloud.githubusercontent.com/assets/10619135/19456880/9bcc0f52-9491-11e6-805d-b7cb4e0c8db1.png)

No vaccum hoppers, just a random hopper. closing issue.

**Comment by cyberpwnn** [comment] 2016-10-18 22:14
This same area has caused multiple crashes due to hoppers at the given world locations

```
-3959, 50, -5342
-3954, 50, -5342
-3958, 50, -5342
-3954, 48, -5342
-3959, 48, -5342
-3960, 48, -5342
```

**Comment by cyberpwnn** [comment] 2016-10-18 22:17
Im going to check the global crash index to see if this exact crash is happening for others.

**Comment by SwiftSwamp** [comment] 2016-10-18 22:19
Alright

**Comment by cyberpwnn** [comment] 2016-10-18 22:41
The pickaxe used had this configuration 

![image](https://cloud.githubusercontent.com/assets/10619135/19499085/726ac8de-9562-11e6-9e31-752c6955b3a9.png)

**Comment by cyberpwnn** [comment] 2016-10-18 23:07
I checked the source code on craftbukkit and nms to see what was throwing the NullPointerException. It turns out it is likely double chests. 

``` java
Inventory destinationInventory;
// Have to special case large chests as they work oddly
if (iinventory instanceof InventoryLargeChest) 
{
    destinationInventory = new org.bukkit.craftbukkit.inventory.CraftInventoryDoubleChest((InventoryLargeChest) iinventory);
 }

else
{
    destinationInventory = iinventory.getOwner().getInventory();
}
```

**Comment by SwiftSwamp** [comment] 2016-10-19 17:49
How are we going about handling this issue?

**Comment by cyberpwnn** [comment] 2016-10-20 03:02
Redesigning hoppers or canceling the event wont fix it. The event is called after that code. So it would crash before the event hits.

**Comment by cyberpwnn** [comment] 2016-10-20 03:22
Closing this issue. 

The problem is caused by hoppers being chained on double chests like so

![image](https://cloud.githubusercontent.com/assets/10619135/19545262/d9a09e84-9652-11e6-9455-55a403f1c65e.png)

**Closed by cyberpwnn** 2016-10-20 03:22 UTC
Labels: bug, technic, urgent
