### ISSUE TITLE
Water Flow Glitch on Creative server

### ISSUE THREAD

**Issue by kotik1998** [cyberpwnn/GlacialRealms#381] opened 2016-11-04 21:56 UTC
When u cover a water source the rest simply dont dissapear.

EDIT:
It create another source :/  i'm struggling building thing on creaive with water ussage

**Comment by SwiftSwamp** [comment] 2016-11-04 21:59
Suggestion: Add Liquids as a bypass for Hadron's physics controllers

**Comment by cyberpwnn** [comment] 2016-11-06 01:30
"Hadron's physics controllers"

No.

**Comment by cyberpwnn** [comment] 2016-11-06 21:19
Cannot reproduce on development server, needs reproduction steps.

@SwiftSwamp ensure FAP is up to date

**Comment by SwiftSwamp** [comment] 2016-11-08 05:41
We ended up figuring out this was because of Commune, I believe you released Commune with the fix but never closed this?

**Comment by cyberpwnn** [comment] 2016-11-08 12:52
THEN CLOSE IT

**Comment by cyberpwnn** [comment] 2016-11-08 12:52
https://github.com/cyberpwnn/GlacialRealms/issues/364

**Closed by cyberpwnn** 2016-11-08 12:52 UTC
Labels: bug, commune
