### ISSUE TITLE
Skyblock 2 boundary issue

### ISSUE THREAD

**Issue by Dazzzza12** [cyberpwnn/GlacialRealms#267] opened 2016-10-17 00:23 UTC
You can build outside the boundary of your island, if you don't get what I mean it's when you leave your island but you can still carry on building on ( if that makes sense )

**Comment by cyberpwnn** [comment] 2016-10-17 00:54
Assuming you mean any block, not just multi blocks. Its probably something swift needs to change.

**Comment by GetDerpy** [comment] 2016-10-17 06:14
You sure this isn't just cos you're admin?

**Comment by cyberpwnn** [comment] 2016-10-17 06:52
Valid point. Needs confirmation.

**Comment by SwiftSwamp** [comment] 2016-10-17 12:15
Cannot reproduce, protected like it should be. Closed as Dazz forget's he has bypass perms a lot :P

**Closed by SwiftSwamp** 2016-10-17 12:15 UTC
Labels: bug, general
