### ISSUE TITLE
4th Vote link doesn't give a reward

### ISSUE THREAD

**Issue by CombatWombat010** [cyberpwnn/GlacialRealms#723] opened 2017-01-03 11:42 UTC
The new 4th vote link doesn't give out any prizes (money, vote points or voting crate).

**Comment by dragonking1121** [comment] 2017-01-03 13:31
Same I dident get mine

**Comment by cyberpwnn** [comment] 2017-01-03 22:14
It might be because of the web server issues this morning. Can someone re-confirm this is still a problem?

**Comment by dragonking1121** [comment] 2017-01-04 00:58
Confirmed I did it agian dident work

**Comment by SwiftSwamp** [comment] 2017-01-04 04:53
The new Voting Site I added the server to seems to of had some issues, this is now resolved.
The Author was extremely quick about resolving it, so far I'm loving it :)

**Closed by SwiftSwamp** 2017-01-04 04:53 UTC
Labels: bug, general
