### ISSUE TITLE
Items turning into potions during PvP / potential dupe

### ISSUE THREAD

**Issue by GetDerpy** [cyberpwnn/GlacialRealms#235] opened 2016-10-16 01:37 UTC
When pvping, my gapples turned into stacked potions. Later, my sword turned into potions. Seems to be that if you drink a potion and quickly switch back to your gapples/sword, it duplicates the stack of potions. 

Saying potential dupe because if that's the case you could essentially turn say, a stick, into a stack of potions.

**Comment by cyberpwnn** [comment] 2016-10-16 02:12
Coinflip

**Comment by cyberpwnn** [comment] 2016-10-16 02:13
https://www.spigotmc.org/threads/coinflip-csgo-gambling-plugin-paid.148116/page-4#post-1961062

**Comment by GetDerpy** [comment] 2016-10-16 06:50
How is this related to the coinflip issue? Curious.

**Comment by cyberpwnn** [comment] 2016-10-16 13:23
Swift is working on it i beleive. Also, im not sure what coinflip is, or what it does, so i dont know. But @SwiftSwamp is assigned to this issue. he should answer lol.

**Comment by SwiftSwamp** [comment] 2016-10-16 14:13
I'm unable to reproduce this, could you record and post a video? Also, I believe we got mixed up and thought this was the same thing regarding the Coinflip GUI Opening during PvP.

**Comment by cyberpwnn** [comment] 2016-10-20 03:33
Dead

**Closed by cyberpwnn** 2016-10-20 03:33 UTC
Labels: bug, general, urgent
