### ISSUE TITLE
Silk touch and /bs are not picking up spawners

### ISSUE THREAD

**Issue by xadistic** [cyberpwnn/GlacialRealms#685] opened 2016-12-21 04:19 UTC
I originally had 75 iron golem spawners and I was using /bs holding a silk pick and it would mine them but they wouldnt come to my inventory. they just disappeared. I lost 21 spawners just now and would like to get them back...

https://youtu.be/g7UMYKuI2HY

proof of it happening

**Comment by SwiftSwamp** [comment] 2016-12-21 20:44
Are you using Magnetic Boots?

**Comment by CondensateTribe** [comment] 2016-12-21 23:53
I will do some testing. Ill report my findings (with an alt and with my admin account)

**Comment by xadistic** [comment] 2016-12-22 00:00
I was using AntiGravity boots

**Comment by CondensateTribe** [comment] 2016-12-22 00:47
During my testing, 100% of the spawners that I broke were magnetically going to me. What else did you have on your boots besides AntiGravity?

**Comment by cyberpwnn** [comment] 2016-12-22 02:55
You need to meet the following conditions to use /bs

* No Magnetic boots (or any boots affecting item pickup)
* Be able to pay the mining cost (if on factions)
* Have inventory space to collect the spawner (one empty slot)
* Must have a silk touch pickaxe IN YOUR HAND

You do NOT need to meet the following conditions 
 
* You do not need to be in territory you can construct in
* You do not need to actually SEE the spawner (behind a wall works if you own it)

If the following conditions are met and you still cannot mine it, it means **you did not place the spawner** or **data was lost regarding who placed it**

This is a Nest persistence data issue. It will be fixed in the future.

**Comment by xadistic** [comment] 2016-12-22 02:58
I was on a solo island, completely empty inventory, glacial boots with
antigravity 1, and had placed all 75 ig spawners alone. Ashley did the test
as well and did not pickup some.

**Comment by cyberpwnn** [comment] 2016-12-22 03:00
Then it is most likely data persistence issues. This will resolve itself once im finished with the HYVE API

**Comment by xadistic** [comment] 2016-12-22 03:02
Alright good to hear.

**Comment by cyberpwnn** [comment] 2016-12-22 03:02
Im closing this for now since the issue is caused by a parent issue. If you have any extra info on this, please report it here (even though its closed i still read it)

**Closed by cyberpwnn** 2016-12-22 03:02 UTC
Labels: bug, missing information
