### ISSUE TITLE
Cannot use Ender Pearls when Jumping / Mid Air

### ISSUE THREAD

**Issue by SwiftSwamp** [cyberpwnn/GlacialRealms#311] opened 2016-10-21 14:50 UTC
When you're jumping and you're still in mid air you cannot use Ender Pearls for the reason "Please stand on solid ground to use that", I'm not entirely sure if it's meant to be like this or if it was just forgotten about but if it won't still allow the glitch, could we allow it when jumping?

**Comment by cyberpwnn** [comment] 2016-10-22 17:09
Tell me how im supposed to see if they are flying?

**Comment by GetDerpy** [comment] 2016-10-25 00:09
Check if /fly is enabled and just say "Cannot use enderpearls when fly is enabled"?

**Comment by cyberpwnn** [comment] 2016-10-25 01:13
By doing that, you can glitch into bases. The problem is when they turn on hack fly, just for a split second they have a window of time to get through a base. You and leblanc proved that to me.

**Comment by cyberpwnn** [comment] 2016-10-26 18:30
Closing this. If anyone has an idea on how to do this, re-open it and explain.

**Closed by cyberpwnn** 2016-10-26 18:30 UTC
Labels: bug, commune, open discussion
